name: Психосоматика — MVP
description: Roadmap-driven проект для мобільного додатку з AI-агентом
public: false

views:
  - name: 🗺️ Roadmap
    type: roadmap
  - name: 🧩 Kanban
    type: board
  - name: 🔎 Backlog
    type: table
    filters:
      labels: ["backlog"]
  - name: 📅 Timeline
    type: roadmap

fields:
  - name: Status
    data_type: single_select
    options:
      - name: 🧠 Idea
        color: gray
      - name: ✍️ Specification
        color: yellow
      - name: 🛠️ In Progress
        color: blue
      - name: 🔍 QA
        color: orange
      - name: ✅ Done
        color: green

labels:
  - feature
  - bug
  - AI
  - auth
  - chat
  - UI
  - infra
  - nice-to-have
  - MVP
  - blocked
  - urgent
  - low-priority

milestones:
  - name: MVP Back
    description: Створення основного бекенду, бази даних, API
  - name: MVP Front
    description: Фронтенд-додаток на React Native
  - name: AI Routing
    description: Інтеграція GPT-агента для маршрутизації
  - name: Test & Polish
    description: Тестування і доопрацювання функціоналу
  - name: Release
    description: Публікація у сторах, підготовка маркетингових матеріалів